# Chapter 08 Numpy & Matplotlib




## 8-x Numpy 綜合練習





EX 1: 將 arr 中的所有奇數替換成 -1。

輸入：

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

期望輸出：

array([ 0, -1, 2, -1, 4, -1, 6, -1, 8, -1])

In [ ]:
# Write your code here








EX 2: 

寫一函式 trans1Dto2D(array)，可任意輸入 1D numpy 陣列，
回傳為 2 列的 2D numpy 陣列。

輸入：

trans1Dto2D(np.array([2,3,5,3,1,3,4,6]))
期望輸出：

array([[2, 3, 5, 3],
 [1, 3, 4, 6]])


輸入：

trans1Dto2D(np.arange(18))

期望輸出：

array([[ 0, 1, 2, 3, 4, 5, 6, 7, 8],
[ 9, 10, 11, 12, 13, 14, 15, 16, 17]])

輸入：

trans1Dto2D(np.arange(20))

期望輸出：

array([[ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [ ]:
#Write your code here

def trans1Dto2D(x):
    
    

EX 3: 

試產生下面兩個 1D numpy 陣列，在轉成 2D numpy 陣列後，將之垂直堆疊起來。

輸入：
a = array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
b = array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

期望輸出：

array([[0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9],
 [1, 1, 1, 1, 1],
 [1, 1, 1, 1, 1]])

In [ ]:
# Write your code here


EX 4: 

若 a,b,c 等三個 1D numpy 陣列分別如下，試垂直堆疊 a, b, c 以得到一個 2D numpy 陣列 arr。

再將 arr 中的第一列(row)與第二列進行交換。

輸入：
a = array([0, 1, 2, 3, 4])
b = array([1., 1., 1., 1., 1.])
c = array([0., 0., 0., 0., 0.])

期望輸出：

array([[1., 1., 1., 1., 1.],
 [0., 1., 2., 3., 4.],
 [0., 0., 0., 0., 0.]])
 

In [ ]:
# Write your code here




In [ ]:
EX 5: 
    
對於 txt 資料，在 Numpy 裡可以使用.loadtxt 或是 np.genfromtxt 來讀取它。

下面輸入的程式可以下載 iris data 的第一個維度(花萼的長度)，共 150 資料，

試求其平均值(np.mean())、中位數(np.median())和標準差(np.std())。

輸入：


url = 'https://archive.ics.uci.edu/ml/machine -learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

期望輸出：

5.843 5.8 0.825



In [ ]:
# Write your code here
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine -learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])




EX 6: 

承續上題，試將 iris sepallength 的資料進行正規化，使其值的分布介於 0到 1 之間。



In [ ]:
# Write your code here
import numpy as np


url = 'https://archive.ics.uci.edu/ml/machine -learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])




EX 7: 

過濾 iris_2d 的資料，找出滿足 petallength(第三行) > 1.5 和 sepallength(第一行) < 5.0 的所有列。

輸入：

url = 'https://archive.ics.uci.edu/ml/machine -learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

期望輸出：

array([[4.8, 3.4, 1.6, 0.2],
 [4.8, 3.4, 1.9, 0.2],
 [4.7, 3.2, 1.6, 0.2],
 [4.8, 3.1, 1.6, 0.2],
 [4.9, 2.4, 3.3, 1. ],
 [4.9, 2.5, 4.5, 1.7]])
 

In [ ]:
# Input
import numpy as np

url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])


EX 8: 

試撰寫一個函式 mindivmax(array)，該函式能將傳入的 numpy 2D 陣列之所
有 列 (row)的 最 大 值 與 最 小 值 求 出 ， 並 且 回 傳 每 一 列 計 算 最 小 值 /最 大 值
(min-by-max)的結果。

輸入：

mindivmax(np.array([[9, 9, 4],[8, 8, 1],[5, 3, 6],[3, 3, 3],[2, 1, 9]]))

期望輸出：

array([0.44444444, 0.125 , 0.5 , 1. , 0.11111111])

In [ ]:
#Write your code here

def mindivmax(array):
    
    
    
    
    
    

EX 9: 
    
試 實 現 一 個 能 計 算 兩 個 1D numpy 陣 列 之 間 的 歐 幾 里 得 距 離 的 函 式 norm(a,b)。

輸入：

norm(np.array([1,2,3,4,5]),np.array([4,5,6,7,8]))


期望輸出：

6.7082

In [ ]:
# Write your code here
